# OpenCar Configuration
project:
  name: my-opencar-project
  version: 1.0.0

perception:
  models:
    - yolov8
    - segformer
  confidence_threshold: 0.5

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
